# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4ea6f46a40a7deaa2097b86a63550a24c72b0e0e067951fbddb00aeab2d47806de712aebff909023a266235ab183ba7da22a13b60d80f58a85f3bdedba83f49

test:
  secret_key_base: 94504d5059e83f1c7c26e9396a8ab6c914ea4ced7e75441430e1a1bce35f045124bb1b195dd1f6125e10da53471a2937d233403658bb0c6708d5e0628026984d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
